[phases.setup]
nixPkgs = ["ffmpeg", "python3", "curl", "fontconfig", "which"]

[phases.install]
cmds = [
  "npm install",
  "curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp",
  "chmod 755 /usr/local/bin/yt-dlp",
  "which yt-dlp",
  "yt-dlp --version"
]

[start]
cmd = "node src/index.js"
